apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: notes-app
  labels:
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: notes-app-api:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: api-config
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
